### ISSUE TITLE
List of view routes

### ISSUE THREAD

**Issue by florian-callewaert** [Ajerbouh/ASID20.2-projet-FAH#4]
### ROLE_ANONYMOUS

- **User**:
    - form-login
    - form-signup

- **Conferrence**: 
    - conf-list-rated
    - conf-list-unrated
    - conf-read
    - conf-list-search (page of search results)

- **Home**:
    - list of all conferrences (with pagination)

### ROLE_USER

- **User**:
  - form-current-user-update (with delete button, with modal confirmation)

- **Conferrence**: 
  - conf-read => add rating button
- **Rating**:
  - form-rating-create

### ROLE ADMIN

- **UserAdmin**:            
  - form-admin-user-create
  - form-admin-user-update
  - admin-user-list => button delete and button update (redirect to form-admin-user-update)

- **ConferenceAdmin**:            
  - form-admin-conf-create
  - form-admin-conf-update
  - admin-conf-list-top-ten
  - admin-conf-list => button delete and button update (redirect to form-admin-conf-update)

- **RatingAdmin**:        X

**Comment by HassanAriz** [comment]
- template routes missing
